### ISSUE TITLE
Check extension works with Manifest V3

### ISSUE THREAD

**Issue by anthonyec** [anthonyec/powerlet#15]
I heard about some changes at the Chrome Dev Summit [talk about extensions](https://www.youtube.com/watch?v=7-ALJiZCI6w).

https://developer.chrome.com/extensions/migrating_to_manifest_v3

**Comment by xprnio** [comment]
According to an issue on [Vimium's Github repo](https://github.com/philc/vimium/issues/4331), it doesn't seem like it (at least not as far as I understand). Hence, please don't rush with upgrading to manifest v3 until either [w3c figures user-scripts out](https://github.com/w3c/webextensions/issues/279) or [you're forced to](https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/).

**Comment by anthonyec** [comment]
@xprnio thanks for the heads up and links. But yeah, I've been holding off upgrading to manifest v3 for this very reason. Waiting to see what happens with the proposed [user scripts API](https://github.com/w3c/webextensions/blob/main/proposals/user-scripts-api.md)

**Comment by anthonyec** [comment]
#85
