### ISSUE TITLE
Feedback / Feature Requests

### ISSUE THREAD

**Issue by ricobl** [anthonyec/powerlet#61]
Thanks for this lovely extension, I've been looking for something like this for a while.

Have you considered expanding the search to regular bookmarks as well? VSCode's quick open dialog searches for files by default and typing `>` searches for commands. Something like this would be great for keyboard navigation. Perhaps using `Cmd+K` for bookmarks and `Cmd+Shift+K` for bookmarklets.

I see that not all bookmarklets work transparently. For example: trying to use jQuery (`$`) from a page that has it exposed globally works when clicking from the bookmark bar but not from the extension. Is this a limitation from the extension environment?

I noticed references to a code editor in the source. Are there plans to allow editing bookmarklets as well? That would be awesome!

**Comment by anthonyec** [comment]
@ricobl not sure if you still use this extension. But just to let you know, a big part of Powerlet was rewritten recently to support some Chrome changes. And as a result, the jQuery issue should be fixed now!

**Comment by ricobl** [comment]
Hey @anthonyec! Yeah, I'm still using it, I gave using globals like jQuery a try and it seems to be working indeed, great job migrating to the manifest v3. Thanks for getting back to me!
