### ISSUE TITLE
Work out how to officially release for Firefox

### ISSUE THREAD

**Issue by anthonyec** [anthonyec/powerlet#8]

**Comment by madacol** [comment]
Did you publish it to the firefox addons store? https://addons.mozilla.org/en-US/firefox/addon/powerlet/

I haven't been able to find a reference that it was you

**Comment by anthonyec** [comment]
Yup that's me! I forgot about this issue, I haven't given much attention to the FireFox version

**Comment by anthonyec** [comment]
I'll update the FireFox version soon and make it clearer it's official
