### ISSUE TITLE
Readability Bookmarklet Fails to Run

### ISSUE THREAD

**Issue by taylordolan** [anthonyec/powerlet#81]
Hi there, thanks so much for your work on this extension! Without it I'd have to switch from Arc back to Chrome.

For some reason I can’t get [this Readability bookmarklet](https://stephanango.com/tidy) to work in Powerlet. (For reference, the source is [here on GitHub](https://github.com/kepano/tidy/blob/main/tidy.js).)

It works as a normal bookmarklet in Chrome, but when I try to run the script from Powerlet, I get `Uncaught ReferenceError: Readability is not defined` in the console. This happens in both Arc and Chrome.

**Comment by anthonyec** [comment]
Thanks for reporting! This is related to how Chrome executes custom scripts in their own "world", they don't have access to global variables.

There is a way to [execute scripts in the same world as the page](https://developer.chrome.com/docs/extensions/reference/scripting/#type-ExecutionWorld) in the latest version of Chrome's extension API (manifest v3), though currently I can't upgrade Powerlet to that until some APIs are supported. 

Soo there would need to be some other way execute the script, possibly injecting a `<script>` tag into the page. I'll need to experiment!

**Comment by taylordolan** [comment]
Hiya! I missed your earlier response, but I noticed just today that it works in the latest version. Thanks for the fix!

**Comment by anthonyec** [comment]
> Hiya! I missed your earlier response, but I noticed just today that it works in the latest version. Thanks for the fix!

Ah yes, I forgot to update you on this. Glad it's working now, thanks for letting me know!
